### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by robrich82** [lavkumarv/swagger-to-slate#2]
Whether I try and convert the yaml, json or both I am getting this error.
`TypeError: Cannot read property 'replace' of undefined
    at Object.keys.map.response (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\responses.js:11:68)
    at Array.map (native)
    at Object.parse (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\responses.js:10:28)
    at Object.keys.map.method (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\path.js:52:33)
    at Array.map (native)
    at Object.parse (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\path.js:24:23)
    at Object.keys.map.path (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\convert.js:54:45)
    at Array.map (native)
    at convertToMd (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\convert.js:53:45)
    at Object.<anonymous> (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\index.js:46:5)
PS C:\Users\robri\Downloads> npm update -g
PS C:\Users\robri\Downloads> swagger-to-slate -i .\swagger.json
TypeError: Cannot read property 'replace' of undefined
    at Object.keys.map.response (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\responses.js:11:68)
    at Array.map (native)
    at Object.parse (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\responses.js:10:28)
    at Object.keys.map.method (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\path.js:52:33)
    at Array.map (native)
    at Object.parse (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\objects\path.js:24:23)
    at Object.keys.map.path (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\convert.js:54:45)
    at Array.map (native)
    at convertToMd (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\src\convert.js:53:45)
    at Object.<anonymous> (C:\Users\robri\AppData\Roaming\npm\node_modules\swagger-to-slate\index.js:46:5)`

**Comment by lavkumarv** [comment]
Sorry, For the late reply. I am looking into it. I will fix it within few hours.

**Comment by startswithaj** [comment]
I'm also getting this error, its to do with using $ref @lavkumarv did you figure it out?

**Comment by lavkumarv** [comment]
Thanks, @danieljoppi for solving the issue. Now it is fixed.
