### ISSUE TITLE
SyntaxError...

### ISSUE THREAD

**Issue by rlyle** [lavkumarv/swagger-to-slate#4]
Pretty sure this is probably some configuration issue on my end, but when I try to run your tool I get the following error:

rlyle@rlyle-VirtualBox:~/local_work/calypso/docs/api$ swagger-to-slate
/usr/local/lib/node_modules/swagger-to-slate/src/objects/path.js:11
  let pathParameters = null 
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/swagger-to-slate/src/convert.js:5:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

rlyle@rlyle-VirtualBox:~/local_work/calypso/docs/api$ node --version
v4.2.6
rlyle@rlyle-VirtualBox:~/local_work/calypso/docs/api$ npm --version
5.4.1

**Comment by rlyle** [comment]
Never mind, NodeJs woefully out of date on Ubuntu... upgraded to 6.0 and the problem went away.
